### ISSUE TITLE
Laravel

### ISSUE THREAD

**Issue by nilportugues** [phpbarcelona/meetup-speakers#1]
Hello everyone involved! You all know me already I'm into PHP Barcelona and any other PHP event in town. 

I just wanted everyone know I'm the owner of the Laravel-Barcelona meetup. I registered the group due to its popularity and I'm sure something can be done with it.

No event has been celebrated, yet, nor have I started looking a place to celebrate it or speakers. It's not even a newborn or has birth date planned, but people are showing interest in it.

I'm sure we can make use of it too to announce events there too, and pretty much anything we feel its convenient.

**Comment by motanelu** [comment]
Hi Nil, sure thing, let's touch base at the next PHP meetup and discuss it then at length.

**Comment by smoya** [comment]
Thanks @nilportugues. Let's talk, as @motanelu said, at the next PHP Meetup.

Closing the issue.
