### ISSUE TITLE
Loosely coupled DDD

### ISSUE THREAD

**Issue by juanangosto** [phpbarcelona/meetup-speakers#2]
---

level: beginner-advanced?
twitter: @juanangosto
## email: juan@juanangosto.com

Everyone and his mother nowadays is charmed by DDD, but it's so easy to couple yourself into the mermaid song of a framework...

At ofertix.com we are refactoring our codebase following the DDD principles while fighting against our beloved Symfony for some space, like a marriage.

So the talk would drive from basic DDD principles to how easy is to couple yourself into the framework, then how to prevent the framework to taint the domain layer and finally how to put it at the service of the application.

**Comment by motanelu** [comment]
Hi Juan,

Thank you for your proposal. Currently we're looking for speakers for the May event. Would you be interested in giving the talk then?

**Comment by juanangosto** [comment]
Yes, sure. 

Regards,

Juan Angosto

**Comment by juanangosto** [comment]
@montanelu May I go through any kind of approval or can I prepare the talk for May already?

**Comment by smoya** [comment]
Hi @juanangosto. We accept your proposal for May. We will send you an email once we know where the meetup will take place.

**Comment by juanangosto** [comment]
Thanks @smoya. Ofertix is willing to provide the place for the meetup if you are interested.

**Comment by kbsali** [comment]
@Juan that's great news, could you tell a bit more about the place? Where
exactly is it and how many attendees could you host?

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=kevin@saliou.name&idSignature=22

**Comment by kbsali** [comment]
@Juan is the office is in Sant Just (like Google says ;)) ?
If that's the case than i'm afraid it won't be possible to host the even
there as it is to far from the city center. We would like to keep the
gathering in Barcelona to make it easier for everybody to attend.
Is that ok with you? The event in May will most probably take place at
Skyscanner, right in Plaça Catalunya!

Cheers!
Kevin

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=kevin@saliou.name&idSignature=22

**Comment by juanangosto** [comment]
Yes, it's there. We can't call it close to the center of the city. 

It's OK to me to go to Skyscanner, I really like that place.

**Comment by smoya** [comment]
Hi @juanangosto ,

The meetup will take place on 10th May, at Skyscanner's Offices. 

It's everything fine for you?

Thanks

**Comment by juanangosto** [comment]
Yes, sure. I'll be ready on May 10th.

**Comment by motanelu** [comment]
Done - Thank you @juanangosto!
