### ISSUE TITLE
Functional PHP

### ISSUE THREAD

**Issue by eloipoch** [phpbarcelona/meetup-speakers#4]
Hi,

I'm Eloi Poch, a Backend Developer currently working at Akamon.

Today I've attended the meetup (thanks Typeform and organizers) expecting learn new tricks or ways to use functional concepts in PHP because we have been doing it for a while at Akamon and it seemed a great opportunity.

After the talk I've thought that I can do another one with the same topic but from a different point of view. I've asked about it to some organizers and the guy who did the talk (sorry, I do not remember your name) and the idea liked to all of them so here I am.

I need to think about how to structure the talk but I guess it will have:
- Main aspects of functional programming (why we want to apply them in PHP)
- Production code (examples)
- Existent libraries (we are not alone)
- Drawbacks that we can have doing all of this (it is PHP, not Clojure)

I would like to do the talk in Spanish (or Catalan) because I'm not fluent in English but if it is a must I'll still consider do the talk.

Thanks :)

**Comment by smoya** [comment]
Hi @eloipoch,

We are really happy with your proposal. However, We only have one free slot for May's meetup.
I'm gonna mark your talk proposal as "May proposal" and let other people send us other talks and vote them.

We will get back to you two weeks before the meetup. That works for you?

Cheers!

**Comment by eloipoch** [comment]
It's fine by me @smoya

**Comment by smoya** [comment]
Hi @eloipoch ,

because **Functional programming** was the topic of one of the talks in the last meetup, we decided to postpone yours until June. I hope you understand our decision. Are you happy to do it on June's meetup?

Thanks.

**Comment by eloipoch** [comment]
Perfect 😄

**Comment by kbsali** [comment]
Hi @eloipoch ,

we have a problem with 1 of the speakers of next week's meetup...
would you be able to get your talk ready by then?
We would need an answer asap please so we can arrange other options if you could not do it!

thx!

**Comment by eloipoch** [comment]
Hi @kbsali, 

I haven't started it yet and this weekend I'm out so I will not be able to do it.
Sorry.

**Comment by vguardiola** [comment]
Hi Eloi, we are planning a meetup on 17th November, You are interested in doing this talk on November meetup?

Thanks

**Comment by eloipoch** [comment]
If it's not in english is fine for me.
But it will be amazing if I can have another week to prepare it. This weekend I/m going to try finish [La Behovia](http://www.behobia-sansebastian.com/) and I'm going to stay in San Sebastian a couple of days more with some friends.

**Comment by vguardiola** [comment]
Hi Eloi I change your proposal for January, do you think that can you do it?

**Comment by eloipoch** [comment]
Perfect 👍

**Comment by dcorto** [comment]
@eloipoch save the 26th of January for your talk! Okay? 

Thanks!
