### ISSUE TITLE
When CQRS meets Event Sourcing

### ISSUE THREAD

**Issue by sdepablos** [phpbarcelona/meetup-speakers#6]
Hi,

I'm Sergi de Pablos, CTO at Ulabox. For the last year and a half we've been developing all our new internal apps with DDD and we would like to share with the community some of the thing we've learned so far. We know there are some good resources to learn it (the blue and red book, DDD in PHP) but we think developers always enjoy seeing new approaches, real use cases, and specially code. 

Our talk would be centered on a new app we've been developing for the last six months, a warehouse management system created in PHP, with CQRS and Event Sourcing (there're no persisted entities, only events that generate projections used in the read model). 

We know there was already a DDD talk this month, but ours takes a totally different approach and DDD is a issue important enough to repeat (we also think nobody has tried ES with PHP in a real app in Barcelona, so it would be a first for a lot of people). We already have it, and after a first internal talk we're just polishing a few things. 

Would it be possible to make the talk this June or it's already fully booked? We wouldn't like to wait up until September (we know that July / August are bad months to do a talk). In case is already booked, would it be possible to do a second event or it's too much? The thing is that is a 50 minutes talk, and we don't think we could reduce it anymore or would even make any sense.

Regarding the place, we don't have enough space at our office, but we can manage to find a place big enough for at least 100-120 people. 

Regards,

S.

P.S: the developer doing the talk asked to do it in Spanish, he does not feel confident enough to do it in English (kudos to Juan Angosto for doing it).

**Comment by kbsali** [comment]
Hi @sdepablos,

thanks for the proposal, it sounds very interesting indeed!
We will discuss this with the other members of the team, but here are a few comments: 
- it's kind of annoying that it can only be held in Spanish... anyway he could train to do it in English? We do have quite a few persons who don't speak nor understand Spanish that well...
- 50min is not ideal as we decided we would go for shorter talks so we have the chance to get more in 1 night; but I guess it's no big deal if we do it once! :) To be discussed with the others
- You mentioned being able to find a big place, able to host 100-120 persons, any hint on where it is? And do you know how flexible they are in terms of dates? Because we still haven't decided when we would program the next meetup, but the decision is usually driven by the availability of the venue!

Thanks!

**Comment by 0xaguspunk** [comment]
> we prefer talks to be delivered in English or Spanish

**Comment by kbsali** [comment]
@armellini13 so English is ok? :)

**Comment by sdepablos** [comment]
Hi @kbsali,

We have developers for whom English would not be an issue, but we'd like for the one that created the talk to be the one to do the talking. The problem is that if the talk is in English the technical level will be badly impacted, we would all learn little, and in that case, what is the point of having a PHP meetup? Just to see familiar faces? ;)

Let's us think about this issue over the weekend

**Comment by kbsali** [comment]
I'm not against doing in Spanish! It's only that from day one in the group of organizers we said we would do it all in English (having 2 non-spanish speakers in the group help taking that decision! :) ).
But anyway, given that we already have 2 "short" english talks for June, what we could do is 2 events! 1 Spanish-only with your talk, and another 1 english only...
We just need to decide on the dates and venues!

**Comment by sdepablos** [comment]
@kbsali, I hope you don't count yourself among the non-Spanish speakers ;) As there is gonna be also a short presentation, do we need to shorten ours (~50 mins)? We would prefer not to, the talk as it is now in almost too short to explain everything.

Regarding the venue, I'm talking with some people today about the one hundred people place, I'll keep you informed.

**Comment by sdepablos** [comment]
Ok, we have the [Ironhack](https://www.google.es/maps/place/Ironhack/@41.3977351,2.1903,15z/data=!4m2!3m1!1s0x0:0xfe5222819e3b6768?sa=X&ved=0ahUKEwiU_I2tkfPMAhUESRoKHZ_jAykQ_BII2QIwLQ) space, June 22nd, I suppose at 19, I'll let you know tomorrow. Ulabox takes care of the catering.

Title: PHP Barcelona Meetup - Jun([ey]|io) 2016
Short description: **When CQRS meets Event Sourcing** - Manel Sellés (@manelselles) software engineer.

Manel will post the long description.

**Comment by manelselles** [comment]
---

level: advanced
twitter: @manelselles

## email: manelselles@gmail.com

Have you ever wondered how all this CQRS / ES concepts could be applied to a PHP project? Let's take a look at some code of our last project: a warehouse management system.

This talk will show how we understand DDD and how we apply it at Ulabox, what changes in application's architecture and code when we apply CQRS and how to deal with event sourcing, when there're no persisted entities, only events that generate projections used in the read model.

**Comment by sdepablos** [comment]
Sorry guys,

It looks like the people at Ironhack created their [own meetup](http://www.meetup.com/ironhack-barcelona/events/231387655/). I never specifically said that the event was going to be created at the Barcelona PHP Meetup, but I thought it was understood. I suppose they wanted to get something on return for hosting the event (I've been "growth hacked"). Anyway, in case you still want to create the event at the PHP Meetup, I think it would be easier if you close the RSPV and point the talk to the Ironhack one.
