### ISSUE TITLE
Code metrics in PHP

### ISSUE THREAD

**Issue by liopic** [phpbarcelona/meetup-speakers#8]
Hi, I'm Julio Martínez, fullstack developer working at ulabox since last year.

As one of ulabox's in-house weekly training sessions, I did a presentation on code quality tools in PHP, with some real examples. I think it could be nice to share this talk with the local community too, as I have never seen a talk on this issue.

The talk introduces some code metrics concepts with easy examples, and how to obtain them in PHP using tools like phploc, phpdepend, phpmetrics, etc. It follows with a discussion on which metrics are relevant, how we are already using them in some projects and how we should evaluate them in our department.

The original presentation takes 1 hour, but I could reduce it to the very basic if the time limit is 30 minutes. I'd love to do the talk in Spanish, as I did in ulabox's training session, but if it's a must I could elaborate it in English.

**Comment by dcorto** [comment]
Hi @liopic thanks for the proposal :)

You can do the talk in Spanish, no problem. 

We are planning the next meetup on 1st December, its okay for you? 

@vguardiola if something is wrong, please correct me :)

**Comment by vguardiola** [comment]
No problem, spanish or english

**Comment by liopic** [comment]
I'm sorry but I can't do it on 1st December, as we have an event at the office. But any other date (for instance, 15th) is ok.

**Comment by dcorto** [comment]
Ok, we are looking forward for confirm a venue on 15th and confirm with the other speaker. We stay in touch.

Thanks
